### ISSUE TITLE
no skill cost [BUG]

### ISSUE THREAD

**Issue by msdreadful** [ncs-sl/support-en#1]
**Describe the bug**
When using a skill on someone it does not have any cost

**To Reproduce**
1. Use any offensive or healing skill on someone (not yourself)

**Expected behavior**
It should have some cost to stam, racial or health

**Desktop (please complete the following information):**
 - OS: -
 - Viewer: Firestorm
 - Viewer Version: -

**Comment by ezebongiovi** [comment]
Thanks for the report! I was able to reproduce we will work on that **ASAP**. I'm updating the issue's description to be more clear. 🥇

**Comment by ezebongiovi** [comment]
@msdreadful It has been fixed and updated on the Meter Provider at [**LANDMARK**](https://maps.secondlife.com/secondlife/Tawa/68/18/82)
