### ISSUE TITLE
[BUG] NCS Meter v1.0.1: URL passed to llHTTPRequest is not valid

### ISSUE THREAD

**Issue by Horusmubble** [ncs-sl/support-en#102]
## Describe the bug
I got the NCS Meter v1.0.1: URL passed to llHTTPRequest is not valid
 everytime i wear the meter , happends after levelling up to level 10,

## To Reproduce
Just wear the meter and wait till the initialization and the error suddenly appear 

### Desktop (please complete the following information):
 - Windows 10 64 bit
 - Viewer Firestorm 64 bit version 6.4.21.64531
 -

## In-Game name
Horus Mubble

**Comment by ezebongiovi** [comment]
Duplicated of https://github.com/ncs-sl/support-en/issues/82
