### ISSUE TITLE
[BUG]  not available  for fighting.

### ISSUE THREAD

**Issue by H4RV1** [ncs-sl/support-en#18]
I don't know if it is a bug but when you toggle "turn not available for fighting." and someone is attacking me, I still  got killed.

**Comment by ezebongiovi** [comment]
@H4RV1 Fixed on v1.0.2. I would need you to comment this issue with your in-game name so I can reward you

**Comment by H4RV1** [comment]
Thanks for taking care of the issue, and for the xp reward I've got☻
it's good to see someone actually taking care of the issues and improving the mtr.
