### ISSUE TITLE
Teamheal doesn't appear to work

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#21]
I assume it should heal everybody nearby in the same Group.  How close must the others be standing to have it take effect?
It would be helpful if there were more information about this in the Wikki.

I tried it with people between 6 and 20m and nothing seemed to happen.

**Comment by ezebongiovi** [comment]
Fixed in v1.0.2

**Comment by MorphLupindo** [comment]
Please give the XP to RocketRaccoonGalaxyGuardian

**Comment by MorphLupindo** [comment]
Thanks!  I received the XP.
