### ISSUE TITLE
Gender pronouns seem to be wrong for certain skills

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#23]
[09:56] NCS Meter v1.0.1: Fedderik Nyoki a sudden rush of anger makes her dangerously tough!

Here's one example.  I've seen this a couple of times.

**Comment by ezebongiovi** [comment]
Thank you for the report. The issue has been identified and fixed. We will release the fix with `v1.0.2`. Please provide me with your in-game name so I can reward you for this

**Comment by MorphLupindo** [comment]
My in-game name is Morph Lupindo

**Comment by MorphLupindo** [comment]
Thanks!  XP received.
