### ISSUE TITLE
Stamina decreases just by running back and forth

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#31]
When I run back and forth, my stam drops.  Each time i turn around and run back, it goes down by 1%.

https://gyazo.com/88ee687af176cc06aad2f1ded28a9b3d

**Comment by ezebongiovi** [comment]
That's not a bug. Running consumes stamina, no matter the direction you run. Same when you jump and your health is damaged.

**Comment by MorphLupindo** [comment]
Ah, ok.  Can it go by points rather than %?  A level 10 shouldn't get more tired than a level 1 when they run  :)
