### ISSUE TITLE
When you take off/put on meter, your health and stam return to 100%

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#40]
Say you've got 10 health and 10 stam.  If you relog, you go to 100%, 100%.

The health and stam should stay the same through a meter on/off.

**Comment by AguilaKubrick** [comment]
We will thest that but it supossed to be locked to the actual points until you stop recieving damge for at least 10 mins. After that time yes, they will get full again, that feature is intended only to prevent players to recover using that trick.

**Comment by ezebongiovi** [comment]
@MorphLupindo I just tested it and it looks like it's working. Please make sure that 10 minutes have not passed since last time you received damage. I'll close the issue, feel free to re-open if the issue persists on your end. 

Thank you for helping us to improve dude, you are a rockstar!! 🥇 🎸
