### ISSUE TITLE
Show/Hide stats not working (inconsistent)

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#41]
I was unable to turn off my stat display. Sometime it works, other times not.

https://gyazo.com/5e69b82d1aa0dba6720f6c3361fa6fcb

**Comment by AguilaKubrick** [comment]
Meter stats are automatically shown when you recieve damage, it will normally remain being shown for a given time after you stop recieving damage. For that reason you won't be able to hide your stats until they timed up.
