### ISSUE TITLE
If your avatar is silenced by a skill (like dart?) then there should be a CONFUSED or SILENCED label above your head

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#44]
You should have a tag above your head - like CONFUSED - if you are darted.

It's just like if you are armed or buffed.

**Comment by ezebongiovi** [comment]
We are not planning to add any status effect to the meter. Instead we are planning to improve that type of "communication" by adding visual effects and particles on next versions, probably `v1.0.3`. 

Also we are planning to add the status effect to the HUD. Right now, we don't know if we are `darn`, `silenced` or something by looking at the HUD. The idea  would be to add icons for each status effect for `v1.0.3` probably, something like this:

![image](https://user-images.githubusercontent.com/8200694/135701345-77ec4248-a8a8-485f-91b6-b20a87a1c41c.png)

**The status effect icons showed in the HUD are 100% illustrative and might change on the final version**
