### ISSUE TITLE
[BUG][23:01] llDialog: all buttons must have label strings [23:01] llDialog: all buttons must have label strings [23:01] llDialog: all buttons must have label strings [23:01] llDialog: all buttons must have label strings

### ISSUE THREAD

**Issue by toxic1631** [ncs-sl/support-en#46]
## To Reproduce
2. Use skill '....'
3. Receive skill '....'

## Screenshots
https://gyazo.com/a3c05c7632ea59c96bb4d87440d72d9c
https://gyazo.com/754d0be17b4e5c0672deb3d1b22ed90b

### Desktop (please complete the following information):
 - OS: [e.g. Windows]
 - Viewer [e.g. Firestorm, Singularity]
 - Viewer Version [e.g. 22]

Firestorm 6.4.21 (64531) Jul 21 2021 21:00:53 (64bit / SSE2) (Firestorm-Releasex64) with Havok support
CPU: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (2904 MHz)
Memory: 32679 MB
Concurrency: 16
OS Version: Microsoft Windows 10 64-bit (Build 19043.1237)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Card Memory: 8192 MB
## In-Game name
toxic Ling

**Comment by ezebongiovi** [comment]
@toxic1631 Fixed in v1.0.2. Please comment with your in-game name so I can reward you 😄

**Comment by toxic1631** [comment]
Awesomeness'! Thank you all...issues has been resolved and ontop of all this I got an amazing exp reward !! I appreciate you all ♥ Bless
