### ISSUE TITLE
Swoon not causing damage on higher levels

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#49]
When I use the Swoon skill to recover racials, it doesn't seem to cause health damage on higher levels (even when it hits)

https://gyazo.com/783a4065cf5deb2b3ac0bc4a9d2fe1a7

**Comment by ezebongiovi** [comment]
Fixed

**Comment by MorphLupindo** [comment]
Got the XP - Thanks for resolving this so quickly!
