### ISSUE TITLE
Getting to a level through respect is different than growing the level from 1

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#53]
When you grow your level starting at 1, you end up with all these Level 1 skills on the right hand side - because you can't just start off with the high levels.   However, if you are a high level and you respect, you don't have to have any of the low level skills.

I'm not sure if this is an issue, but you don't end up in the same place.
(sorry, i'm having a hard time explaining what's going on - maybe i need some coffee :)

**Comment by ezebongiovi** [comment]
It's not a bug, the respec allows you to re specify your character's build. That includes dropping skills you don't want or don't need.

**Comment by MorphLupindo** [comment]
zmetx Resident was “rage fighting” earlier. That’s continually attacking people over and over and attacking them as they’re in the chair trying to heal.

I’ve got video if necessary and can provide it in a few hours.
