### ISSUE TITLE
Lycan-3 reflect doesn't work very well

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#59]
Minimal damage to the person hitting me.  He was buffed so I would have expected he would take a lot of damage.
It burned right through my health.

[16:07] NCS Meter v1.0.1: LeonI Viper applies Ferocity-4 on itself
[16:07] NCS Meter v1.0.1: Morph Lupindo applies Reflect-3 on itself
[16:07] NCS Meter v1.0.1: Morph Lupindo starts reflecting incoming damage
[16:07] NCS Meter v1.0.1: Morph Lupindo have been finished by LeonI Viper

**Comment by ezebongiovi** [comment]
Thank you for the report. It is not actually a bug, but a balacing issue. I'll review it, run some tests and balance the skill if needed.

**Comment by ezebongiovi** [comment]
It has been balanced. The fix should take effect in current version already. We will continue testing the skill and it's progress during levels to understand it's balance point. Thanks for the report!

**Comment by MorphLupindo** [comment]
Hi.  The damage to the lycan is good now.  However, the damage does not reflect onto the attacker (in this case, Gargoyle healer)

**Comment by MorphLupindo** [comment]
Thanks for fixing that!  I got the XP.
