### ISSUE TITLE
Skill balancing on Alien Tyrant - lasts too long

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#91]
Please check out how long the buff/arm skill stays in effect.  It could probably be cut in half and still be near unbeatable.

**Comment by ezebongiovi** [comment]
Thank you for the report. I would need more details, what's the skill you are talking about? I think I can guess, but I must be sure! 😄

**Comment by ezebongiovi** [comment]
See comment: https://github.com/ncs-sl/support-en/issues/94#issuecomment-939366157
