### ISSUE TITLE
Tank - Adamant cooldown[BUG]

### ISSUE THREAD

**Issue by lvlace** [ncs-sl/support-en#98]
## Describe the bug
When using Adamant the notecards say the cooldown is 32 seconds.  When I use it on alien it is 6 seconds.  

## To Reproduce
[23:36:51] NCS Meter v1.0.1: Mace Braveheart applies Adamant-4 on itself
[23:36:57] NCS Meter v1.0.1: Your support skills are ready.

**Comment by ezebongiovi** [comment]
Actually `Adamant` skill's base cooldown is `5 seconds` (grows with level up). So I believe the notecard info you have is wrong.
